### ISSUE TITLE
Update dependencies and publish new version

### ISSUE THREAD

**Issue by paulshryock** [php-stubs/wordpress-seo-stubs#5]
Would it be possible to release a new version of this package with updated dependencies?

Particularly bumping `php-stubs/wordpress-stubs` and `psr/log` to their latest versions?

**Comment by szepeviktor** [comment]
Hello @paulshryock 👋🏻 

Thank you for nagging me.
Here we go: https://github.com/php-stubs/wordpress-seo-stubs/releases/tag/v20.5
Now this package is a bigger mess. Orphan. Comes without guarantee.

**Comment by szepeviktor** [comment]
https://github.com/php-stubs/wordpress-seo-stubs/blob/f12d43a98eac4bded2b4073ebbe7c3b788b0a9bd/composer.json#L14

Could it be any higher?

**Comment by szepeviktor** [comment]
Yoast uses v1
https://github.com/Yoast-dist/wordpress-seo/blob/e1c26f45a23ee4087eacbd8e3dfb31b28e0f125f/composer.json#L32

**Comment by szepeviktor** [comment]
Maybe this helps
```json
"psr/log": "^1.0 as 2.0"
```
or in reverse ...

**Comment by szepeviktor** [comment]
Wait @paulshryock!
I've decided to care about it.
All dependencies are removed! https://github.com/php-stubs/wordpress-seo-stubs/commit/7a1436ce312d7d919c957f27db64df62f36d13c3

Packagist may serve the previous state for a short time as I've overwritten 20.5

**Comment by paulshryock** [comment]
Amazing, thanks @szepeviktor! I will try installing the new version.

**Comment by paulshryock** [comment]
I was able to install 20.5, and I see that I have the correct version with the dependencies removed:

<img width="506" alt="Screenshot 2023-04-21 at 12 14 00 PM" src="https://user-images.githubusercontent.com/7530507/233684972-5c4609dd-6885-43e4-94ae-8ca1d322a256.png">

I found an issue near the end of the generated file, where a PHPDoc block for `wpseo_register_var_replacement` is ended early, which results in some of the functions not being correctly stubbed. This is because of the unescaped `?>`:

<img width="1200" alt="Screenshot 2023-04-21 at 12 14 50 PM" src="https://user-images.githubusercontent.com/7530507/233685113-4de4de96-c376-4412-a121-a8032047f75f.png">

**Comment by szepeviktor** [comment]
I told you so!!
Yoast SEO needs 1000+ hours to become _Yoast stubs_.

Let's see what `sed` can do! :)

**Comment by szepeviktor** [comment]
# ☝🏻

**Comment by szepeviktor** [comment]
@paulshryock Please try [v20.5.1](https://youtu.be/1_tbMz8xPMM?t=244)!

**Comment by paulshryock** [comment]
I see what you mean. I certainly appreciate the effort. Thanks for that patch release! I will give it a try.
